name: Testing
onn: push

jobs:
  test_project:
    runs_on: ubuntu-lastest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip3 install --user django
        python3 manage.py test

